### PR TITLE
docs: change all references of faas to func

### PR DESCRIPTION
**Pull request by lance**
Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Review by lkingland — APPROVED** [review]
LGTM!

**Review by rhuss — COMMENTED** [review]
Looks good to me !

/lgtm
/approve

**Comment by rhuss** [comment]
@lance guess this needs conflicts to be resolved or maybe a new PR needs to be created with the changes applied afresh.

**Comment by lance** [comment]
@rhuss thanks for the reminder. PTAL

**Pull request merged**
