### PR TITLE
rename faas to func

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

Relates: https://github.com/boson-project/faas/issues/201

### CODE REVIEW

**Review by lkingland — APPROVED** [review]
Looks good to me.

**Review by lance — COMMENTED** [review]
Overall LGTM. I think I might have missed some discussion overnight regarding `func` vs. `function`.

**Comment by lance** [comment]
@zroubalik any chance you can resolve these conflicts?

**Comment by zroubalik** [comment]
> @zroubalik any chance you can resolve these conflicts?

@lance absolutely, I missed this PR somehow

**Review by lance — APPROVED** [review]
Lgtm

**Pull request merged**
